PolypApps\Bundle\AuthBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        apikey:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        name:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
    manyToMany:
        serviceid:
            targetEntity: Service
            cascade: {  }
            mappedBy: null
            inversedBy: userid
            joinTable:
                name: user_service
                joinColumns:
                    -
                        name: userid
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: serviceid
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
