polyp_apps_auth_homepage:
    pattern:  /
    defaults: { _controller: PolypAppsAuthBundle:Default:index }
polyp_apps_auth_login:
    pattern: /login
    defaults: { _controller: PolypAppsAuthBundle:Default:login }