polyp_apps_auth_homepage:
    pattern:  /
    defaults: { _controller: PolypAppsAuthBundle:Default:index }
polyp_apps_auth_login:
    pattern: /login
    defaults: { _controller: PolypAppsAuthBundle:Default:login }
    methods: [POST]
polyp_apps_auth_login_with_service:
    pattern: /loginwithservice
    defaults: { _controller: PolypAppsAuthBundle:Default:loginWithService }
    methods: [POST]