parameters:
#    polyp_apps_auth.example.class: PolypApps\Bundle\AuthBundle\Example

services:
#    polyp_apps_auth.example:
#        class: %polyp_apps_auth.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
